version: '3.9'

services:
  sitesadmin:
    image: ${DOCKER_REGISTRY-}sitesadmin-${BUILD_NUMBER}
    container_name: sitesadmin
    env_file:
      - ${ENV_PATH}
    ports:
      - "5000:5000"
    networks:
      - sitesadmin-net
    volumes: 
      - ${HOST_ASSETS_DIRECTORY}:/assets:rw
    build:
      context: .
      dockerfile: ./src/SitesAdmin/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=5000
networks:
  sitesadmin-net:
    driver: bridge