version: '3.9'

services:
  sitesadmin:
    networks:
      - database 
    volumes:
      - sitesadmin-data-protection-keys:/home/app/.aspnet/DataProtection-Keys:rw
networks:
  database:
    external: true
volumes:
  sitesadmin-data-protection-keys: